# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

from pylatexenc.latexencode import unicode_to_latex

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('../../_ext'))


# -- Project information -----------------------------------------------------

project = 'Cryptographic Documentation'
# copyright = '???'
author = 'Rohde & Schwarz'

# The full version, including alpha/beta/rc tags
release = '1.5.0'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'botan_src_path',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The master toctree document.
root_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for botan_src_path extension ------------------------------------

# ATTENTION ON RELEASE
# ATTENTION ON RELEASE
# ATTENTION ON RELEASE
#
#   Change this to the Botan GitHub tag this document is referring to,
#   before cutting a revision of the crypto documentation.
#
#   TODO: Add a more reliable way or some sort of checklist to avoid
#         forgetting this before cuttung a release.
#
# ATTENTION ON RELEASE
# ATTENTION ON RELEASE
# ATTENTION ON RELEASE
src_ref_reference = '3.1.1'

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['_static']

# -- Options for LaTeX output ------------------------------------------------

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class], toctree_only).
latex_documents = [
    (root_doc, 'crypto.tex', unicode_to_latex(project), unicode_to_latex(author), 'manual', False),
]

latex_additional_files = [
    'custom.sty'
]

latex_elements = {
    'preamble': r'\usepackage{custom}\usepackage{xfrac}',
    'maketitle': r'\custommanualmaketitle',
}
