
name: Setup CI Environment
description: Set up a build agent with the required environment

inputs:
  env_file:
    description: The .env file containing the environment variables to be provisioned
    required: true

runs:
  using: composite
  steps:
    - name: Set Environment Variables
      run: python3 ${{ github.action_path }}/../../scripts/read_environment.py ${{ inputs.env_file }} >> $GITHUB_ENV
      shell: bash
      if: runner.os != 'Windows'

    - name: Set Environment Variables
      run: python3 ${{ github.action_path }}/../../scripts/read_environment.py ${{ inputs.env_file }}  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh
      if: runner.os == 'Windows'
