project: Changes since last Audit

repo:
  github_handle:  randombit/botan
  local_checkout: ../_build/botan
  audit_ref_from: 3.0.0-alpha1

  # Tip of `master` on the 21st of June 2023
  # TODO: change that to 3.1.0 (or further intermediate steps) eventually
  audit_ref_to:   99dbdd53a9a9ac66e4d4fe710413bb7402f6cb95

topics: topics
cache: ../_build/audit_generator_cache

fail_on_load_error: true
ignore:
  # This patch was merged twice manually. Jack forgot to pull recent changes by
  # the pull request author and created a second merge commit after realizing
  # his mistake. As a result, GH #2944 has references in two merge commits. To
  # avoid issues in the verification scripts we ignore this patch.
  - pr: 2944
