project: Changes since last Audit
rst_ref: changes

repo:
  local_checkout: ../_build/botan

topics: topics
cache: ../_build/audit_generator_cache

fail_on_load_error: true
ignore:
  # This may contain a list of patches that must be ignored by the generator
  # scripts. For instance, when pull requests get merged manually and the script
  # can't deal with the format. Nevertheless, we must make sure that all relevant
  # code changes show up in the audit report regardless.
  #
  # Examples:
  # - pr: 1234
  # - commit: abcd...
