name: CI

on:
  push

permissions:
  contents: read
  # implicitly all other scopes not listed become none

jobs:
  pdf_creation:
    strategy:
      matrix:
        element: [ {name: Crypto Documentation, dir: cryptodoc, out_name: crypto},
                   {name: Audit Method Description, dir: audit_method, out_name: audit_method},
                   {name: Test Specification, dir: testspec, out_name: testspec} ]

    name: Build PDF - ${{ matrix.element.name }}
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ${{matrix.element.dir }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -qq install texlive-latex-extra texlive-fonts-recommended tex-gyre texlive-lang-german latexmk
      - name: Install Python Dependencies
        run: pip install -r requirements.txt
      - name: Build pdf
        run: make latexpdf
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: botan_${{ matrix.element.out_name }}-${{ github.sha }}
          path: ${{ matrix.element.dir }}/_build/latex/${{ matrix.element.out_name }}.pdf

  url_check:
    strategy:
      matrix:
        element:
          - {name: Crypto Documentation, dir: cryptodoc}
          - {name: Test Specification, dir: testspec}

    name: Check source URLs - ${{ matrix.element.name }}
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ${{matrix.element.dir }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Python Dependencies
        run: pip install -r requirements.txt
      - name: Build with URL check enabled
        run: make SPHINXOPTS="-D src_ref_check_url=True -W" html
