title: Build System

patches:
# Feature: Module Lifecycle and Experimental/Deprecated Features  (@reneme)
- pr: 3910  # https://github.com/randombit/botan/pull/3910
  merge_commit: 66dc49e2e245eae128b4e6811215f3ca11a75e0c
  classification: info

# Don't stop the ninja build if errors occur  (@randombit)
- pr: 3952  # https://github.com/randombit/botan/pull/3952
  merge_commit: 626dc641ac0eb90d89febbec207035855910b2d2
  classification: info
