title: Build System

description: |
  This bundles changes to the build system. No relevant changes to the implementation
  of the library are contained here.


patches:
# Preserve file metadata when installing
#   Author:    @bkmgit
#   Approvals: (@randombit)
- pr: 5140  # https://github.com/randombit/botan/pull/5140
  merge_commit: afebb96a0c5e3a4be220463ece6bcf0748f75659
  auditer: falko-strenzke
  classification:  info

# Fix error compiling the Aarch64 cpuid code without os_utils
#   Author:    @randombit
- pr: 5145  # https://github.com/randombit/botan/pull/5145
  merge_commit: 733b29cab37095c9813f69cdcb930efea5db4009
  auditer: falko-strenzke
  classification:  info
# Installed python bindings file is named botan3.py
#   Author:    @bkmgit
#   Approvals: (@randombit)
- pr: 5139  # https://github.com/randombit/botan/pull/5139
  merge_commit: f656d0ef9fb00ed12f4ae3025a34f5f3efe88211
  auditer: falko-strenzke
  classification:  info

# FIX: Don't declare backward compatibility ALIAS for CMake < 3.18
#   Author:    @reneme
#   Approvals: (@randombit)
- pr: 5099  # https://github.com/randombit/botan/pull/5099
  merge_commit: 0d4cd13de1a5977da0df3911fb93cfd443732b69
  auditer: falko-strenzke
  classification:  info

# Partially Revert #4927
#   Author:    @randombit
- pr: 5064  # https://github.com/randombit/botan/pull/5064
  merge_commit: ec6b7b97725e920c3954de4f472d2f0f1d8736cb
  auditer: falko-strenzke
  classification:  info

# fix: use fedora new pem cert location
#   Author:    @carlosrodfern
#   Approvals: (@randombit)
- pr: 5052  # https://github.com/randombit/botan/pull/5052
  merge_commit: 1ce160a4010a0460181e8ca5dcf16c92d8401f77
  auditer: falko-strenzke
  classification:  info

# Add support for building with clang-cl
#   Author:    @solemnwarning
#   Approvals: @reneme, (@randombit)
- pr: 4255  # https://github.com/randombit/botan/pull/4255
  merge_commit: e3f0f7f0df79db57a776219f6abf0aae52726f3e
  auditer: falko-strenzke
  classification:  info
  comment: Also contains some code changes.

# improve botan-config.cmake
#   Author:    @justusranvier
#   Approvals: @reneme
- pr: 5027  # https://github.com/randombit/botan/pull/5027
  merge_commit: 77a3a40a03d145c8c9d5545276a9b864ca0791c3
  auditer: falko-strenzke
  classification:  info

# Rename CMake targets to botan::botan / botan::botan-static
#   Author:    @reneme
#   Approvals: (@randombit)
- pr: 5022  # https://github.com/randombit/botan/pull/5022
  merge_commit: 7fc5a0f5231a1cc1e47d41281b675ce20fe97318
  auditer: falko-strenzke
  classification:  info

# Fix various missing dependencies
#   Author:    @randombit
- pr: 5020  # https://github.com/randombit/botan/pull/5020
  merge_commit: 72deba42e6638516372a40b85190f87f9a076c34
  auditer: falko-strenzke
  classification:  info

# Support for wildcards in module selection
#   Author:    @reneme
#   Approvals: (@randombit)
- pr: 4966  # https://github.com/randombit/botan/pull/4966
  merge_commit: 17a327f63f15986dbecdd94d58b22cd559e50fbd
  auditer: falko-strenzke
  classification:  info

# FIX: Building a static library using Ninja on macOS
#   Author:    @reneme
#   Approvals: (@randombit)
- pr: 4947  # https://github.com/randombit/botan/pull/4947
  merge_commit: 1da353c0e364e81033587ee55e07e18edc85cbfb
  auditer: falko-strenzke
  classification:  info

# Add the concept of an internal feature macro definition
#   Author:    @randombit
- pr: 4948  # https://github.com/randombit/botan/pull/4948
  merge_commit: c0f75cf878df5e1805c93630bf861ef2d83ea774
  auditer: falko-strenzke
  classification:  info

# configure.py: automatically detect what brand CXX=c++ is from --version
#   Author:    @nabijaczleweli
#   Approvals: (@randombit)
- pr: 4933  # https://github.com/randombit/botan/pull/4933
  merge_commit: 359710893b2d5fc4e100c0fd96502b98dcb3ac3b
  auditer: falko-strenzke
  classification:  info

# Fix an issue building System_RNG with only getrandom
#   Author:    @randombit
- pr: 4932  # https://github.com/randombit/botan/pull/4932
  merge_commit: d3f85923574e57558db7014acf25c390dd661303
  auditer: falko-strenzke
  classification:  info

# Remove configure.py options that disable various intrinsics
#   Author:    @randombit
#   Approvals: @reneme
- pr: 4927  # https://github.com/randombit/botan/pull/4927
  merge_commit: 520059d8ecf0552cb7f38e2c48b31db94c191d9b
  auditer: falko-strenzke
  classification:  info

# Remove the --with-local-config build option
#   Author:    @randombit
- pr: 4905  # https://github.com/randombit/botan/pull/4905
  merge_commit: 0c19b62f3309dd69c1ae5d7b1a2d65d19fb23402
  auditer: falko-strenzke
  classification:  info

# FIX: handle multi-arch directories in cmake-config package
#   Author:    @reneme
#   Approvals: (@randombit)
- pr: 4839  # https://github.com/randombit/botan/pull/4839
  merge_commit: 5f82b97d3447f6be64c96d017eeb338e0ec326b0
  auditer: falko-strenzke
  classification:  info

# Install TPM2 libraries for the clang-tidy run
#   Author:    @randombit
- pr: 4831  # https://github.com/randombit/botan/pull/4831
  merge_commit: 2c52b8ac57f722043d64de8d19cea6850505f634
  auditer: falko-strenzke
  classification:  info
  comment: Refactors some TPM-related code also.

# Remove autogen of x509_dn_ub.cpp
#   Author:    @randombit
#   Approvals: @atreiber94
- pr: 4827  # https://github.com/randombit/botan/pull/4827
  merge_commit: eea33d0b513066d55b70ad884363d1e1ade11aa6
  auditer: falko-strenzke
  classification:  info

# Update Android NDK to r28 (January 2025)
#   Author:    @reneme
#   Approvals: (@randombit)
- pr: 4812  # https://github.com/randombit/botan/pull/4812
  merge_commit: 49974bed347a688054165d1ffa14cf47801b3663
  auditer: falko-strenzke
  classification:  out of scope

# Update jitterentropy and work around a build issue in CI
#   Author:    @reneme
#   Approvals: (@randombit)
- pr: 4813  # https://github.com/randombit/botan/pull/4813
  merge_commit: 3f73d3c1be0a3800dede0cb73a399c1c0efd664d
  auditer: falko-strenzke
  classification:  info
  comment: Increment version of jitterentropy to 3.6.2.


# Avoid a single use of Python 3.8 walrus operator in configure.py
#   Author:    @randombit
- pr: 4808  # https://github.com/randombit/botan/pull/4808
  merge_commit: 346317f134cca6ca908d929c42c5088147980348
  auditer: falko-strenzke
  classification:  info

# Try re-enabling modules which MSVC in the past miscompiled
#   Author:    @randombit
- pr: 4805  # https://github.com/randombit/botan/pull/4805
  merge_commit: e16b5f9dac073ee8fbc91cde14ad3120d81e21d6
  auditer: falko-strenzke
  classification:  info

# FIX: dist.py can deal with UTF-8 within `git show`
#   Author:    @reneme
#   Approvals: (@randombit)
- pr: 4801  # https://github.com/randombit/botan/pull/4801
  merge_commit: 6e7dc060c56944256fada3f0943ece3e3e60d89d
  auditer: falko-strenzke
  classification:  info


# FIX: cmake cannot handle version suffix
#   Author:    @reneme
#   Approvals: (@randombit)
- pr: 4802  # https://github.com/randombit/botan/pull/4802
  merge_commit: be539352bd38af4d6ca48fd1ff5042c83381cdac
  auditer: falko-strenzke
  classification:  info

# Add support for GCC ThreadSanitizer [ci skip]
#   Author: Jack Lloyd
- commit: 2344f81004069fd1c8d42ce92d3f6f90734f1536  # https://github.com/randombit/botan/commit/2344f81004069fd1c8d42ce92d3f6f90734f1536
  auditer: TJ-91
  classification: info

# Migrate to native WebAssembly exceptions
#   Author:    @arekmula
#   Approvals: (@randombit)
- pr: 5202  # https://github.com/randombit/botan/pull/5202
  merge_commit: f283c5d29d14f4cea6ac0f43a632f2eaf9b820c6
  auditer: TJ-91
  classification: info

# Remove redundant empty option in emcc flags
#   Author:    @polarnis
#   Approvals: (@randombit)
- pr: 5208  # https://github.com/randombit/botan/pull/5208
  merge_commit: cf0e68e3429f5826b923f26a6b902de13b104870
  auditer: TJ-91
  classification: info

# FIX: Amalgamation build on MSVC x86
#   Author:    @reneme
#   Approvals: (@randombit)
- pr: 5216  # https://github.com/randombit/botan/pull/5216
  merge_commit: b1ff92a4ed98a7fda2e31de3300bca5470f66fff
  auditer: TJ-91
  classification: info

# In configure.py guard against invalid invalid OS/CPU/compiler names
#   Author:    @randombit
#   Approvals: @reneme
- pr: 5215  # https://github.com/randombit/botan/pull/5215
  merge_commit: 46ea9a2a3cf84cbc4a6c66ea3bbe0377a6eed03d
  auditer: TJ-91
  classification: info

# Apply a workaround for GCC miscompilation of Serpent AVX512 in amalgamation mode
#   Author:    @randombit
- pr: 5238  # https://github.com/randombit/botan/pull/5238
  merge_commit: 1ff468fa0508ee12e9cf8de7015da6790610801a
  auditer: TJ-91
  classification: info

# Fix Shellcheck warnings in dev tools directory scripts
#   Author:    @KaganCanSit
#   Approvals: @reneme
- pr: 5250  # https://github.com/randombit/botan/pull/5250
  merge_commit: 87c26d8ba4daa721929551845b7dab645ae7c92e
  auditer: TJ-91
  classification: out of scope

# Remove support for Sun Studio compilers
#   Author:    @randombit
- pr: 5262  # https://github.com/randombit/botan/pull/5262
  merge_commit: 35bfb4c0752ebfc51787860f7ec08bb548b58f18
  auditer: TJ-91
  classification: info

# Enable /Zc:inline with MSVC and clang-cl
#   Author:    @randombit
- pr: 5264  # https://github.com/randombit/botan/pull/5264
  merge_commit: 75167c1a5fb4b1960cb6482c2645e8b0ff3a4bac
  auditer: TJ-91
  classification: info

# Enable BMI2 and GFNI codepaths for MSVC
#   Author:    @randombit
- pr: 5263  # https://github.com/randombit/botan/pull/5263
  merge_commit: 0d718b1467c893e168feaf4d29b61a9681578193
  auditer: TJ-91
  classification: info

# Consistently use ISA target flags
#   Author:    @randombit
- pr: 5276  # https://github.com/randombit/botan/pull/5276
  merge_commit: c6d1196d329963a0168c1e903d5c8ff81c2c4164
  auditer: TJ-91
  classification: info

# Remove support for AltiVec on 32-bit PowerPC
#   Author:    @randombit
#   Approvals: @reneme
- pr: 5266  # https://github.com/randombit/botan/pull/5266
  merge_commit: 7f7dd6c3bbfc4dcb27274bcea637bf9e776ce47b
  auditer: TJ-91
  classification: info

# Don't use ISA flags during compilation anymore
#   Author:    @randombit
#   Approvals: @reneme
- pr: 5297  # https://github.com/randombit/botan/pull/5297
  merge_commit: 8aed85c62d47ed826e2a580f44d46aff87f35d7d
  auditer: TJ-91
  classification: info

# Fix some build dependency issues
#   Author:    @randombit
#   Approvals: @reneme
- pr: 5310  # https://github.com/randombit/botan/pull/5310
  merge_commit: 4bacf4e56ecddd8f97c9e08bd9cca33d7a4e8056
  auditer: TJ-91
  classification: info

# Don't error if a module policy prohibits something which doesn't exist
#   Author:    @randombit
- pr: 4769  # https://github.com/randombit/botan/pull/4769
  merge_commit: b28bdde0a0e974f2efbe9a4f40aa2f0c26075f31
  auditer: falko-strenzke
  classification:  info

# Remove support for configure-time endian checks
#   Author:    @randombit
- pr: 4747  # https://github.com/randombit/botan/pull/4747
  merge_commit: 5a4d7bf6427e07fd95a09ddd447d3a50d88df2b7
  auditer: falko-strenzke
  classification:  info

# Avoid accidentally quadratic code during template processing in configure.py
#   Author:    @randombit
#   Approvals: @reneme
- pr: 4744  # https://github.com/randombit/botan/pull/4744
  merge_commit: dbe3aab1803e8405915304918ac34f600ae8696e
  auditer: falko-strenzke
  classification:  info

# Small build.h cleanups/removals
#   Author:    @randombit
#   Approvals: @reneme
- pr: 4740  # https://github.com/randombit/botan/pull/4740
  merge_commit: 988c634cee6e680e69eebd29e465cef8e0032b0b
  auditer: falko-strenzke
  classification:  info

# Split up versioning info
#   Author:    @randombit
#   Approvals: @reneme
- pr: 4739  # https://github.com/randombit/botan/pull/4739
  merge_commit: 6732b68683355370853b2062e4820646b12d866f
  auditer: falko-strenzke
  classification:  info

# Emit -fPIC or equivalent even for the static library
#   Author:    @randombit
- pr: 4716  # https://github.com/randombit/botan/pull/4716
  merge_commit: 72a870b0ddbd87e03a80f76319f802511c57496f
  auditer: falko-strenzke
  classification:  info

# Make cpuid module optional
#   Author:    @randombit
- pr: 4718  # https://github.com/randombit/botan/pull/4718
  merge_commit: 904d634c2425dc9c645d4af580ab0b634f57aa14
  auditer: falko-strenzke
  classification:  info

# Fix ec_named.cpp generation
#   Author:    @randombit
- pr: 4688  # https://github.com/randombit/botan/pull/4688
  merge_commit: 1f7ae2d6d5990ffb408397e71491e45b18e0ac19
  auditer: falko-strenzke
  classification:  info

# Fixes for LLVM
#   Author:    @randombit
- pr: 4673  # https://github.com/randombit/botan/pull/4673
  merge_commit: 1cce93244f59b3df8f9ea0e0357469b19d52c00d
  auditer: falko-strenzke
  classification:  info

# Sort the OS feature macros
#   Author:    @randombit
- pr: 4654  # https://github.com/randombit/botan/pull/4654
  merge_commit: 15fdc9e3aaa809bc318d0cafaa5b66d9df616f20
  auditer: falko-strenzke
  classification:  info

# Fix a bug in template concat introduced in #4642
#   Author:    @randombit
- pr: 4652  # https://github.com/randombit/botan/pull/4652
  merge_commit: bc555cd3c114497a50b49c4649d6606150881f5b
  auditer: falko-strenzke
  classification: info

# Remove most toggles from build.h
#   Author:    @randombit
#   Approvals: @reneme
- pr: 4639  # https://github.com/randombit/botan/pull/4639
  merge_commit: 5dbdf91528665391f3fc7854b9b760b4c790eefb
  auditer: falko-strenzke
  classification:  info

# Mark generated EC group defines as an internal define [ci skip]
#   Author: Jack Lloyd
- commit: 463b48f947bd41792135cd069d6c2c4def473be2  # https://github.com/randombit/botan/commit/463b48f947bd41792135cd069d6c2c4def473be2
  auditer: falko-strenzke
  classification:  info


# Set sha2_64_armv8 to require armv8crypto also
#   Author: Jack Lloyd
- commit: fa28fc6f4edc344490fab13916a1d6d3dfb7d44b  # https://github.com/randombit/botan/commit/fa28fc6f4edc344490fab13916a1d6d3dfb7d44b
  auditer: falko-strenzke
  classification:  info


# Mark cryptobox module as deprecated, previously missed
#   Author: Jack Lloyd
- commit: 3e40bb9ef2df024828a23e80ee18da4e7c621194  # https://github.com/randombit/botan/commit/3e40bb9ef2df024828a23e80ee18da4e7c621194
  auditer: falko-strenzke
  classification:  info


# Clarify tpm module is TPMv1 only
#   Author: Jack Lloyd
- commit: 6196f58fceada52866472870d87982848354e994  # https://github.com/randombit/botan/commit/6196f58fceada52866472870d87982848354e994
  auditer: falko-strenzke
  classification:  info

# Remove Android Docker build setup [ci skip]
#   Author: Jack Lloyd
- commit: 02415ac51c64c82feb7512a5136303c72cbd0dd2  # https://github.com/randombit/botan/commit/02415ac51c64c82feb7512a5136303c72cbd0dd2
  auditer: falko-strenzke
  classification:  info

# Refactor: CMake Module now uses mostly hard-coded paths
#   Author:    @reneme
#   Approvals: (@randombit)
- pr: 5402  # https://github.com/randombit/botan/pull/5402
  merge_commit: fac269140ef72bff3bd648351bdd58315bf11b02
  auditer: falko-strenzke
  classification:  info

# Fix the FFI datecode for 3.11
#   Author:    @randombit
- pr: 5377  # https://github.com/randombit/botan/pull/5377
  merge_commit: 4648c5020c8dcada728452597a2cc28976778ae4
  auditer: falko-strenzke
  classification:  info

# For MSVC debug info prefer embedding into the object file rather than using PDB
#   Author:    @randombit
- pr: 5349  # https://github.com/randombit/botan/pull/5349
  merge_commit: e8d957052240e1777893df0061472203185677a9
  auditer: falko-strenzke
  classification:  info
